#!/bin/bash

# TextBeeOTP OIDC Testing Guide
# This script demonstrates how to test the OIDC endpoints
# Note: For a complete flow, use oauth2-proxy with an external identity provider (Google, GitHub, etc.)

set -e

BASE_URL="${BASE_URL:-http://localhost:3008}"
CLIENT_ID="${CLIENT_ID:-oauth2-proxy}"
CLIENT_SECRET="${CLIENT_SECRET:-test-secret}"
STATE="test-state-123"
NONCE="test-nonce-456"
REDIRECT_URI="http://localhost:4180/oauth2/callback"

echo "========================================="
echo "TextBeeOTP OIDC Testing Guide"
echo "========================================="
echo ""
echo "Base URL: $BASE_URL"
echo "Client ID: $CLIENT_ID"
echo "Redirect URI: $REDIRECT_URI"
echo ""
echo "These tests demonstrate the OIDC provider endpoints."
echo "For a complete authentication flow, deploy oauth2-proxy."
echo ""
echo "========================================="
echo ""

# Test 1: Discovery Endpoint
echo "[TEST 1] OIDC Discovery Endpoint"
echo "=================================================="
echo "URL: GET /.well-known/openid-configuration"
echo ""
echo "Description: Returns OIDC metadata for this provider"
echo ""
echo "Command:"
echo "curl -s http://localhost:3008/.well-known/openid-configuration | jq ."
echo ""
echo "Expected Response:"
echo "  - issuer"
echo "  - authorization_endpoint"
echo "  - token_endpoint"
echo "  - userinfo_endpoint"
echo "  - scopes_supported"
echo "  - response_types_supported"
echo ""
curl -s "$BASE_URL/.well-known/openid-configuration" | jq . || echo "ERROR: OIDC not enabled or endpoint failed"
echo ""
echo ""

# Test 2: Authorization Endpoint
echo "[TEST 2] Authorization Endpoint"
echo "=================================================="
echo "URL: GET /oauth2/authorize"
echo ""
echo "Description: Starts the authorization flow"
echo ""
echo "Required Parameters:"
echo "  - client_id: OAuth client identifier"
echo "  - response_type: 'code' for authorization code flow"
echo "  - scope: Space-separated scopes (openid, profile, email)"
echo "  - redirect_uri: Where to send the code after auth"
echo "  - state: Random value to prevent CSRF attacks"
echo ""
echo "Command:"
echo "curl -s \"http://localhost:3008/oauth2/authorize\\?client_id=$CLIENT_ID\\&response_type=code\\&scope=openid%20profile%20email\\&redirect_uri=$(echo -n $REDIRECT_URI | jq -sRr @uri)\\&state=$STATE\\&nonce=$NONCE\""
echo ""
echo "Expected Response:"
echo "  - In a real flow: Redirects to your IdP's login page"
echo "  - In test mode: May return auth code or error"
echo ""
echo ""

# Test 3: Token Endpoint
echo "[TEST 3] Token Endpoint"
echo "=================================================="
echo "URL: POST /oauth2/token"
echo ""
echo "Description: Exchanges authorization code for tokens (must run after /oauth2/authorize)"
echo ""
echo "Required Parameters (form-urlencoded):"
echo "  - grant_type: Must be 'authorization_code'"
echo "  - code: Authorization code from /oauth2/authorize"
echo "  - client_id: OAuth client ID"
echo "  - client_secret: OAuth client secret"
echo "  - redirect_uri: Must match the original redirect_uri"
echo ""
echo "Note: This requires a valid authorization code from a prior /oauth2/authorize call"
echo ""
echo "Example Command (with test auth code):"
echo "curl -X POST http://localhost:3008/oauth2/token \\"
echo "  -H 'Content-Type: application/x-www-form-urlencoded' \\"
echo "  -d 'grant_type=authorization_code' \\"
echo "  -d 'code=AUTHORIZATION_CODE_FROM_AUTHORIZE' \\"
echo "  -d 'client_id=$CLIENT_ID' \\"
echo "  -d 'client_secret=$CLIENT_SECRET' \\"
echo "  -d 'redirect_uri=$REDIRECT_URI'"
echo ""
echo "Expected Response (on success):"
echo "  - access_token: JWT token for API access"
echo "  - id_token: JWT with user identity claims"
echo "  - token_type: 'Bearer'"
echo "  - expires_in: Token lifetime in seconds"
echo ""
echo ""

# Test 4: UserInfo Endpoint
echo "[TEST 4] UserInfo Endpoint"
echo "=================================================="
echo "URL: GET /oauth2/userinfo"
echo ""
echo "Description: Returns authenticated user information (requires valid access token)"
echo ""
echo "Required Header:"
echo "  - Authorization: 'Bearer ACCESS_TOKEN'"
echo ""
echo "Note: Requires a valid access_token from /oauth2/token endpoint"
echo ""
echo "Example Command (with test access token):"
echo "curl -s http://localhost:3008/oauth2/userinfo \\"
echo "  -H 'Authorization: Bearer ACCESS_TOKEN_FROM_TOKEN_ENDPOINT' | jq ."
echo ""
echo "Expected Response (on success):"
echo "  - sub: Subject (user ID)"
echo "  - email: User email (if scope includes 'email')"
echo "  - name: User display name (if scope includes 'profile')"
echo "  - Other claims based on requested scopes"
echo ""
echo ""

# Test 5: Health Check
echo "[TEST 5] Health Check Endpoint"
echo "=================================================="
echo "URL: GET /oauth2/health"
echo ""
echo "Description: Checks if OIDC provider is running"
echo ""
echo "Command:"
echo "curl -s http://localhost:3008/oauth2/health | jq ."
echo ""
echo "Expected Response:"
echo "  - status: 'ok'"
echo ""
curl -s "$BASE_URL/oauth2/health" | jq . || echo "ERROR: Health check failed"
echo ""
echo ""

# Info: Standalone OTP
echo "[INFO] Standalone OTP Authentication"
echo "=================================================="
echo "In addition to OIDC, this server provides standalone OTP endpoints:"
echo ""
echo "Send OTP Code:"
echo "  URL: POST /otp/send"
echo "  Required: { recipient: 'user@example.com' or '+1234567890' }"
echo "  Returns: { sessionId: '...' }"
echo ""
echo "Verify OTP Code:"
echo "  URL: POST /otp/verify"
echo "  Required: { sessionId: '...', code: '123456' }"
echo "  Returns: { valid: boolean }"
echo ""
echo "Example:"
echo "  1. Send OTP: curl -X POST http://localhost:3008/otp/send"
echo "     -H 'Content-Type: application/json'"
echo "     -d '{\"recipient\":\"user@example.com\"}'"
echo "  2. Verify OTP: curl -X POST http://localhost:3008/otp/verify"
echo "     -H 'Content-Type: application/json'"
echo "     -d '{\"sessionId\":\"...\",\"code\":\"123456\"}'"
echo ""
echo ""

echo "========================================="
echo "For Complete OAuth2 Flow Testing:"
echo "========================================="
echo "1. Deploy oauth2-proxy with this server as OIDC provider"
echo "2. Configure an external identity provider (Google, GitHub, etc.)"
echo "3. oauth2-proxy handles the interactive login flow"
echo "4. This server validates tokens and returns user info"
echo ""
echo "========================================"
